# Copyright 2024 The Milton Hirsch Institute, B.V.
# SPDX-License-Identifier: Apache-2.0

name: Create release PR
on: workflow_dispatch
jobs:
  release-pr:
    environment: publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.RELEASE_PLZ_GITHUB_TOKEN }}

    - name: Run release-plz
      uses: MarcoIeni/release-plz-action@v0.5
      with:
        command: release-pr
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_GITHUB_TOKEN }}
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
